Installation:
Ubuntu users can use a repository on Launchpad. To add the repo, open a terminal and copy&paste

sudo add-apt-repository ppa:ok2cqr/ppa
sudo apt-get update
sudo apt-get install cqrlog

Only Ubuntu 14.04 and Ubuntu 16.04 are officially supported but there are also builds for other versions of Ubuntu on Launchpad.

Debian users can simply install using the package manager

----
sudo apt-get install cqrlog
----

For other distributions, you can use binaries located at http://cqrlog.com/download. Some of them, like Fedora and Arch, have their own repositories for CQRLOG - Fedora: https://apps.fedoraproject.org/packages/cqrlog ArchLinux https://aur.archlinux.org/packages/cqrlog/
If upgrading, no important file will be overwritten. Anyway, backup your log before you begin any upgrade!

Dependencies:

* IMPORTANT: HamLib - must be installed even if you don't want radio control. The sources are available at http://hamlib.sourceforge.net/, however precompiled packages are available for almost all major Linux distributions.

* MySQL server and client - The MySQL client must be installed, without this the program will not work at all. A MySQL server must be reachable, either on the local machine or via a network.

* libssl-devel needed if you want to use LoTW and/or online log upload 
